### ISSUE TITLE
Request: Remove GPL V3 License?

### ISSUE THREAD

**Issue by jaredjones** [githotto/osxgmp#2]
Would it be possible for you to move from a GPL V3 license towards an MIT or BSD liberal style license instead? The GPL V3 makes it to where I can't use this library in closed source software. This means that if I wanted to upload an iOS app or an OS X application to the app store, I'd also have to place the source code for my application on GitHub under a GPL license.

Hopefully you consider this.
-Jared

**Comment by jaredjones** [comment]
If you're not willing or not allowed to switch to MIT or BSD perhaps you could at least switch this to the Lesser GPL V3 instead? That way I can use the library in closed source software.

**Comment by githotto** [comment]
Hi Jared,
Currently I'm not familiar with the Lesser GPL V3 license internals, but your suggestions seems reasonable to change it. I'll look at it this weekend to see what I can do about it. Thanks for your interest!

**Comment by githotto** [comment]
Dear Jared,
I changed the license type to Lesser GPL V3 and added two functions (factorial, prime) for which I haven't made a unit-test yet. Next weekend I'll hope to find some time for it. Would you please mention or add a reference to your closed software project in which you plan to use the OSXGMP, such that I can start making a list of usage/users of it. Thanks in advance, and good luck with your software!
