### ISSUE TITLE
Newbie error

### ISSUE THREAD

**Issue by darinkaplan** [githotto/osxgmp#3]
Sorry if this is a simple problem, but I'm new to these libraries.  I tried running the osxgmp in swift right out of the box and I'm getting the following error: 

dyld: Library not loaded: /usr/local/lib/libgmp.10.dylib
  Referenced from: /Users/Darin/Library/Developer/Xcode/DerivedData/OSXGMP-dupgwcumawaoencfvlgewtvmcogs/Build/Products/Debug/OSXGMP
  Reason: image not found

Any ideas what I'm doing wrong?

Thanks,

Darin Kaplan

**Comment by githotto** [comment]
Hello Darin,
Sorry to hear that its not working out of the box. I'll have to look at it this weekend, but another user found the following solution (see issue#1):
    'I found the solution just copy "libgmp.10.dylib" in GMP to "/usr/local/lib/libgmp.10.dylib"'
So if you're not afraid of some terminal.app commands use something like:
sudo cp PATH_TO_GMP/libgmp.10.dylib /usr/local/lib
in the Terminal.app, where PATH_TO_GMP is you're installed path to the OSXGMP/GMP in which the libgmp.10.dylib can be found.
Hope this will help (for the moment), and again I'll look at it this weekend and hope to find a fix for this.
Good luck, and thanks for trying.

**Comment by darinkaplan** [comment]
OK, that worked.  Just confused as to why I had to create an entire new folder /usr/local/lib.  Why isn't it the file just stored in an application directory?

**Comment by githotto** [comment]
When you compile the GNU GMP standalone, it places its libraries and header files in the standard Unix directories being /usr/local/lib and /usr/local/include. The moment I started the OSXGMP project I didn't realize that the default dependencies between the libgmp.a and libgmp.10.dylib where used. This weekend I'll try to solve this, by removing the /usr/local/lib/libgmp.10.dylib dependency from the OSXGMP project.
Glad to hear that the 'fix' solved your issue.
