### ISSUE TITLE
Swift 2.0

### ISSUE THREAD

**Issue by peternicholls** [githotto/osxgmp#4]
Thanks for this library! Just a courtesy to let you know BigInt.swift and Main.swift update to latest Swift syntax in Xcode 7 / Swift 2.0 and code will not compile due to "!" in BingInt.swift 

![screen shot 2015-06-16 at 08 08 38](https://cloud.githubusercontent.com/assets/519525/8177659/effb0494-13fe-11e5-97d7-3ff7c852ad9a.png)

**Comment by githotto** [comment]
Hi Peter,
Thanks for your information. I created and pushed a swift2.0_xcode7.0beta branch which solve the
new Xcode7.0beta/Swift2.0 compiler issues. All XCTests ran successfully, so I hope you can continue to use the OSXGMP with the new Xcode/Swift.

**Comment by githotto** [comment]
Changed branch-names. Master now contains the Swift2.0 code-base (suitable for Xcode7 only!), whereas the Swift1.2 branch contains the code-base for Swift1.2 (suitable for Xcode6.4 or Xcode7).
