### ISSUE TITLE
Bigint.swift fails to compile in Xcode 7 on Yosemite )S X 10.10

### ISSUE THREAD

**Issue by johnblommers** [githotto/osxgmp#5]
There are three compiler errors in Bigint.swift. Lines 39, 42, and 45 are flagged with the error and line 36 is the line with which these three lines conflict. The error messages are replicated three times:

Initializer 'init(nr:)' with Objective-C selector 'initWithNr:' conflicts with previous declaration with the same Objective-C selector.

Note that one needs to let Xcode 7 convert the Swift syntax to the new version as well.

Otto can you spare some time to address this problem. My Swift skills are minimal and not up to the task of fixing this.

Many thanks!
- John

**Comment by githotto** [comment]
Hi John,

Thanks for your comment / suggestions. I was late at home, so couldn't see
your early message; hope its in time for you.

I already had a swift2/xcode7beta-branch (June 17th this year) in which the
above errors where solved. Didn't know that the official Xcode was
released. Installing the Xcode7 took quit a long time for me this evening
(especially that all kinds of Xcode6 plugins were removed by Apple without
asking).

I changed the README.md in the hope that people load the appropriate branch
depending on their Swift / Xcode versions being installed. If you download
the swift2.0_xcode7.0 branch code it should compile and run in Xcode7 / OSX
10.10.

Just let me know if its not working, and I'll hope to find some time
tomorrow afternoon to fixt them.
Thanks again for your interest and email.
Kind regards,
Otto van Verseveld

2015-09-19 1:56 GMT+02:00 johnblommers notifications@github.com:
